name: submit-azure-machine-learning-job

trigger:
- none

variables:
  service-connection: 'machine-learning-connection' # replace with your service connection name
  resource-group: 'devops-rg' # replace with your resource group name
  workspace: 'amlws001' # replace with your workspace name

jobs:
- job: SubmitAzureMLJob
  displayName: Submit AzureML Job
  timeoutInMinutes: 300
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: UsePythonVersion@0
    displayName: Use Python >=3.8
    inputs:
      versionSpec: '>=3.8'

  - bash: |
      set -ex
      az version
      az extension add -n ml
    displayName: 'Add AzureML Extension'

  - task: AzureCLI@2
    name: submit_azureml_job_task
    displayName: Submit AzureML Job Task
    inputs:
      azureSubscription: $(service-connection)
      workingDirectory: 'cli/jobs/pipelines-with-components/nyc_taxi_data_regression'
      scriptLocation: inlineScript
      scriptType: bash
      inlineScript: |
        # Submit component job and get the run name
        job_name=$(az ml job create --file single-job-pipeline.yml -g $(resource-group) -w $(workspace) --query name --output tsv)
        
        # Wait for job completion
        az ml job show -n $job_name -g $(resource-group) -w $(workspace) --query status -o tsv
        
        # Wait until the job completes
        while true; do
          status=$(az ml job show -n $job_name -g $(resource-group) -w $(workspace) --query status -o tsv)
          echo "Current status: $status"
          
          if [[ "$status" == "Completed" ]]; then
            echo "Job completed successfully"
            break
          elif [[ "$status" == "Failed" || "$status" == "Canceled" ]]; then
            echo "Job failed or was canceled"
            exit 1
          fi
          
          echo "Waiting for job completion..."
          sleep 30
        done